package co.uk.gokul.letscook.core.common.util

/**
 * Maps a country name to its corresponding flag emoji.
 *
 * This utility provides a quick way to get visual representation for geographic areas
 * when images or icons are not provided by the API.
 *
 * @param countryName The name of the country (case-insensitive).
 * @return A string containing the flag emoji, or a default world globe icon if the country is not mapped.
 */
fun getFlagEmoji(countryName: String): String {
    return when (countryName.lowercase()) {
        "afghanistan" -> "🇦🇫"
        "albania" -> "🇦🇱"
        "algeria" -> "🇩🇿"
        "andorra" -> "🇦🇩"
        "angola" -> "🇦🇴"
        "antigua and barbuda" -> "🇦🇬"
        "argentina" -> "🇦🇷"
        "armenia" -> "🇦🇲"
        "aruba" -> "🇦🇼"
        "australia" -> "🇦🇺"
        "austria" -> "🇦🇹"
        "azerbaijan" -> "🇦🇿"
        "bahamas" -> "🇧🇸"
        "bahrain" -> "🇧🇭"
        "bangladesh" -> "🇧🇩"
        "barbados" -> "🇧🇧"
        "belarus" -> "🇧🇾"
        "belgium" -> "🇧🇪"
        "belize" -> "🇧🇿"
        "benin" -> "🇧🇯"
        "bermuda" -> "🇧🇲"
        "bhutan" -> "🇧🇹"
        "bolivia" -> "🇧🇴"
        "bosnia and herzegovina" -> "🇧🇦"
        "botswana" -> "🇧🇼"
        "brazil" -> "🇧🇷"
        "brunei" -> "🇧🇳"
        "bulgaria" -> "🇧🇬"
        "burkina faso" -> "🇧🇫"
        "burundi" -> "🇧🇮"
        "cambodia" -> "🇰🇭"
        "cameroon" -> "🇨🇲"
        "canada" -> "🇨🇦"
        "cape verde" -> "🇨🇻"
        "cayman islands" -> "🇰🇾"
        "central african republic" -> "🇨🇫"
        "chad" -> "🇹🇩"
        "chile" -> "🇨🇱"
        "china" -> "🇨🇳"
        "colombia" -> "🇨🇴"
        "costa rica" -> "🇨🇷"
        "croatia" -> "🇭🇷"
        "cuba" -> "🇨🇺"
        "cyprus" -> "🇨🇾"
        "czechia" -> "🇨🇿"
        "denmark" -> "🇩🇰"
        "djibouti" -> "🇩🇯"
        "dominica" -> "🇩🇲"
        "dominican republic" -> "🇩🇴"
        "dr congo" -> "🇨🇩"
        "ecuador" -> "🇪🇨"
        "egypt" -> "🇪🇬"
        "el salvador" -> "🇸🇻"
        "equatorial guinea" -> "🇬🇶"
        "eritrea" -> "🇪🇷"
        "estonia" -> "🇪🇪"
        "ethiopia" -> "🇪🇹"
        "faroe islands" -> "🇫🇴"
        "fiji" -> "🇫🇯"
        "finland" -> "🇫🇮"
        "france" -> "🇫🇷"
        "gabon" -> "🇬🇦"
        "gambia" -> "🇬🇲"
        "georgia" -> "🇬🇪"
        "germany" -> "🇩🇪"
        "ghana" -> "🇬🇭"
        "gibraltar" -> "🇬🇮"
        "greece" -> "🇬🇷"
        "greenland" -> "🇬🇱"
        "grenada" -> "🇬🇩"
        "guadeloupe" -> "🇬🇵"
        "guam" -> "🇬🇺"
        "guatemala" -> "🇬🇹"
        "guernsey" -> "🇬🇬"
        "guinea" -> "🇬🇳"
        "guinea-bissau" -> "🇬🇼"
        "guyana" -> "🇬🇾"
        "haiti" -> "🇭🇹"
        "honduras" -> "🇭🇳"
        "hong kong" -> "🇭🇰"
        "hungary" -> "🇭🇺"
        "iceland" -> "🇮🇸"
        "india" -> "🇮🇳"
        "indonesia" -> "🇮🇩"
        "iran" -> "🇮🇷"
        "iraq" -> "🇮🇶"
        "ireland" -> "🇮🇪"
        "israel" -> "🇮🇱"
        "italy" -> "🇮🇹"
        "ivory coast" -> "🇨🇮"
        "jamaica" -> "🇯🇲"
        "japan" -> "🇯🇵"
        "jersey" -> "🇯🇪"
        "jordan" -> "🇯🇴"
        "kazakhstan" -> "🇰🇿"
        "kenya" -> "🇰🇪"
        "kosovo" -> "🇽🇰"
        "kuwait" -> "🇰🇼"
        "kyrgyzstan" -> "🇰🇬"
        "laos" -> "🇱🇦"
        "latvia" -> "🇱🇻"
        "lebanon" -> "🇱🇧"
        "lesotho" -> "🇱🇸"
        "liberia" -> "🇱🇷"
        "libya" -> "🇱🇾"
        "liechtenstein" -> "🇱🇮"
        "lithuania" -> "🇱🇹"
        "luxembourg" -> "🇱🇺"
        "madagascar" -> "🇲🇬"
        "malawi" -> "🇲🇼"
        "malaysia" -> "🇲🇾"
        "maldives" -> "🇲🇻"
        "mali" -> "🇲🇱"
        "malta" -> "🇲🇹"
        "mauritius" -> "🇲🇺"
        "mexico" -> "🇲🇽"
        "moldova" -> "🇲🇩"
        "mongolia" -> "🇲🇳"
        "montenegro" -> "🇲🇪"
        "morocco" -> "🇲🇦"
        "mozambique" -> "🇲🇿"
        "myanmar" -> "🇲🇲"
        "namibia" -> "🇳🇦"
        "nepal" -> "🇳🇵"
        "netherlands" -> "🇳🇱"
        "new zealand" -> "🇳🇿"
        "nicaragua" -> "🇳🇮"
        "niger" -> "🇳🇪"
        "nigeria" -> "🇳🇬"
        "north korea" -> "🇰🇵"
        "north macedonia" -> "🇲🇰"
        "norway" -> "🇳🇴"
        "oman" -> "🇴🇲"
        "pakistan" -> "🇵🇰"
        "palestine" -> "🇵🇸"
        "panama" -> "🇵🇦"
        "papua new guinea" -> "🇵🇬"
        "paraguay" -> "🇵🇾"
        "peru" -> "🇵🇪"
        "philippines" -> "🇵🇭"
        "poland" -> "🇵🇱"
        "portugal" -> "🇵🇹"
        "puerto rico" -> "🇵🇷"
        "qatar" -> "🇶🇦"
        "republic of the congo" -> "🇨🇬"
        "romania" -> "🇷🇴"
        "russia" -> "🇷🇺"
        "rwanda" -> "🇷🇼"
        "saint lucia" -> "🇱🇨"
        "samoa" -> "🇼🇸"
        "san marino" -> "🇸🇲"
        "saudi arabia" -> "🇸🇦"
        "senegal" -> "🇸🇳"
        "serbia" -> "🇷🇸"
        "seychelles" -> "🇸🇨"
        "sierra leone" -> "🇸🇱"
        "singapore" -> "🇸🇬"
        "slovakia" -> "🇸🇰"
        "slovenia" -> "🇸🇮"
        "solomon islands" -> "🇸🇧"
        "somalia" -> "🇸🇴"
        "south africa" -> "🇿🇦"
        "south korea" -> "🇰🇷"
        "south sudan" -> "🇸🇸"
        "spain" -> "🇪🇸"
        "sri lanka" -> "🇱🇰"
        "sudan" -> "🇸🇩"
        "suriname" -> "🇸🇷"
        "sweden" -> "🇸🇪"
        "switzerland" -> "🇨🇭"
        "syria" -> "🇸🇾"
        "taiwan" -> "🇹🇼"
        "tajikistan" -> "🇹🇯"
        "tanzania" -> "🇹🇿"
        "thailand" -> "🇹🇭"
        "togo" -> "🇹🇬"
        "tonga" -> "🇹🇴"
        "trinidad and tobago" -> "🇹🇹"
        "tunisia" -> "🇹🇳"
        "turkey" -> "🇹🇷"
        "turkmenistan" -> "🇹🇲"
        "tuvalu" -> "🇹🇻"
        "uganda" -> "🇺🇬"
        "ukraine" -> "🇺🇦"
        "united arab emirates" -> "🇦🇪"
        "united kingdom", "uk", "british" -> "🇬🇧"
        "united states", "usa", "american" -> "🇺🇸"
        "uruguay" -> "🇺🇾"
        "uzbekistan" -> "🇺🇿"
        "vanuatu" -> "🇻🇺"
        "venezuela" -> "🇻🇪"
        "vietnam" -> "🇻🇳"
        "yemen" -> "🇾🇪"
        "zambia" -> "🇿🇲"
        "zimbabwe" -> "🇿🇼"
        else -> "🌐" // Default world icon for unknown
    }
}
